ToString now uses GetType.Name
Patisson4/KysectStartupProject pull request #7
Opened 2021-04-09 10:11 UTC by Patisson4

to review

2021-04-09 18:55 UTC, annchous requested changes
Самое глобальное замечание: у нас (то есть у шарпистов) **один класс =** (практически всегда) **один файл**. Так что все свои классы распредели по отдельным `.cs` файлам с названием как у класса (`class Task` => `Task.cs`). Когда поправишь то, что я отметила, я ещё раз просмотрю твоё решение и, возможно, запрошу ещё некоторые изменения, удачи)

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +namespace ConsoleApp1
Даже тестовый проект нужно называть как-то более показательно)
Ещё очень важно: не вижу у тебя .csproj файла - файла с конфигурацией проекта. Когда мы пишем на C#, мы работаем с такими единицами, как класс, проект, решение. В решении может быть несколько проектов, в проекте несколько классов. По крайней мере без файла проекта твоё приложение не запустится 👀

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +    internal class SubTask
Классы в C# по умолчанию и так `internal`, так что если ты решил сделать класс `internal` писать модификатор явно не обязательно. Ремарка на тему доступности класса: с какой целью ты хотел сделать класс `internal`? Так ли это важно? Если нет, то, может, стоит сделать класс `public`? Если ты создашь второй проект, который, условно, будет работать чисто как консольный принтер, то ты не сможешь получить доступ к `internal` классу оттуда, как-то так.

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +    internal class SubTask
Замечание к логике наименования класса: почему subtask? Это ведь **под**задача. Если бы я услышала такое название класса, то я могла бы предположить, что такое класс может быть наследником класса `Task`, однако в твоём случае это не так. Даже несмотря на иерархическую точку зрения класс подзадача без класса задача звучит не очень)

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +        protected uint Id { get; }
Здорово, что пишешь `Id`, а не `ID`, как многие часто привыкли делать, но что не очень вяжется с неймингом в шарпах) Но тут у меня вопрос к `protected` модификатору: кто же будет тем счастливым наследником, которому будет предоставлен доступ к `Id`? Если ты рассчитывал сделать иерархию `Subtask : Task`, то тогда не забудь переименовать класс, если не планировал - то вполне можно сделать `Id` приватным (приватные поля именуются с нижнего подчёркивания, camel case'ом с маленькой буквы).

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +        internal string TaskInfo { get; }
По поводу `internal` модификатора уже говорила)

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +        public SubTask(uint currentId, string info)
Вместо `currentId` можно просто `id`)

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +            Manager l = new TaskManagerBase();
Можно упростить `Manager` до `var` и не нужно экономить на буквах (`l`) ))

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +        protected internal uint NextId { get; protected set; } = 0;
По умолчанию `uint` и так 0

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +            var tsk = new SubTask(NextId, value);
Зачем сэкономил одну буковку и испортил слово =D Сделай `task`)

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +            NextId++;
Использовал `TryAdd`, но никак не воспользовался полезной информацией - возвращаемым значением этого метода. Что делать, если он вернёт `false` (и что это вообще означает)? Ты в любом случае увеличиваешь Id следующей задачи, но ведь если добавить задачу не удалось, то и `Id` не следует увеличивать.

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +        public override void Remove(uint id) //rename to Erase?
Не надо переименовывать, так ок)

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +        }
Как-то неудобно так парсить, не так ли?) Советую прочитать про [json сериализацию](https://metanit.com/sharp/tutorial/6.5.php) и воспользоваться прочитанным)

2021-04-09 18:55 UTC, annchous commented on ConsoleApp1/Program.cs
> +            if (Convert.ToBoolean(CountCompleted))
В чём потребность сделать проверку на наличие выполненных задач именно методом конвертирования в `boolean` значение?) Почему не `CountCompleted > 0`?

2021-05-15 19:00 UTC, annchous requested changes

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/ConsolePrinter.cs
> +        [Obsolete("Used for Newсomer")]
Довольно неожиданное применение этого атрибута. В принципе, ты понял его смысл, но, учитывая то, что в новой версии тестового задания отсутствует деление на Newcomer/Сектант, ненужный метод можно вообще убрать.

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +        }
Вижу, что ты решил реализовать индексатор. На мой взгляд, здесь есть проблема, заключающаяся в том, что при использовании его в коде не очевидно, к чему ты обращаешься, пока не зайдёшь в код менеджера. Пример:
https://github.com/Patisson4/KysectStartupProject/blob/4308887dd6d226b950ad7cd26ddeb6723f3abf4d/StartingTaskManagerProject/Program.cs#L83
Могу предложить конкретизировать название менеджера, назвав его `TaskManager`

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +        public bool Add(T obj)
Обычно такие методы (которые возвращают булево значение при попытке совершения какого-то действия над коллекцией) называют с приставкой Try (например, `TryAdd`). Но это пока только к сведению. Раз у тебя только один метод по добавлению, можешь оставить так, чтобы не смущать пользователя.

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +            if (!Tasks.TryGetValue(id, out var buf))
Нейминг на `buf` плохой

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +            if (buf.IsCompleted) //what to do if task already completed?
Ну комплитед и комплитед, чего бухтеть-то
Можешь не запариваться и оставить так

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +            if (!Tasks.Remove(id, out var buf))
Нейминг

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Program.cs
> +            //Ctrl+Z to successful stop
Кажется, этот коммент тут точно не к месту) Пользователь же не станет рыться в коде, чтобы понять, как остановить программу. Того, что у тебя есть команды через /, достаточно.

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/SuperTask.cs
> +        public SuperTask(string taskInfo, DateTime? deadline = null, bool isCompleted = false, Manager<Task> subs = null) : base(taskInfo, isCompleted)
Ищи мой коммент про перегрузку для избавления от `= null` в аргументах

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Task.cs
> +        public string TaskInfo { get; } //public for json
Коммент не нужен

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +        [JsonIgnore] public ReadOnlyDictionary<uint, T> Data => new(Tasks); //for upper-level task usages
Комменты не нужны. Если они для тебя - это грустно, хотя бы ты должен понимать свой код без подсказок) Тем более он тут не громоздкий

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +            NextId = obj.NextId;
Случится катастрофа, если по какой-то причине `obj` останется null

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +            var obj = JsonSerializer.Deserialize<Manager<T>>(file.ReadToEnd());
нейминг

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Program.cs
> +                            //check for valid path???
Можешь добавить в метод `Save` проверку. И убрать комментарий тут)

2021-05-15 19:00 UTC, annchous commented on StartingTaskManagerProject/Program.cs
> +                                case < 2:
Лучше это свалить в default, а конкретные случаи обработать нормально

2021-05-15 19:12 UTC, Patisson4 commented on StartingTaskManagerProject/Manager.cs
> +        public Manager(uint nextId = 0, uint countCompleted = 0, SortedDictionary<uint, T> tasks = null)
Если я делаю там проверку на null с помощью ??, то можно не писать отдельный конструктор?
Или с ?? что то не так?
`Tasks = tasks ?? new SortedDictionary<uint, T>();`

2021-05-15 19:14 UTC, Patisson4 commented on StartingTaskManagerProject/SuperTask.cs
> +        public SuperTask(string taskInfo, DateTime? deadline = null, bool isCompleted = false, Manager<Task> subs = null) : base(taskInfo, isCompleted)
Для Manager есть проверка через ??
А Deadline проверяется на null при выводе чтобы не брать какую то конкретную дату за признак отсутствия дедлайна
Или SuperTask не может существовать без дедлайна?

2021-05-15 19:27 UTC, Patisson4 commented on StartingTaskManagerProject/Manager.cs
> +        [JsonIgnore] public ReadOnlyDictionary<uint, T> Data => new(Tasks); //for upper-level task usages
Изначально все-таки большинство свойств хотелось сделать приватными во имя инкапсуляции (это же она? да? да?) Но поняв, что стандартному json десериализатору не справится без публичности этих свойств, с подачи Fredi поменял на public и оставил комментарии, описывающие причину

2021-05-15 19:56 UTC, Patisson4 commented on StartingTaskManagerProject/Program.cs
> +                            //check for valid path???
Тут вопрос вот в чем. Если у программы есть доступ, и название файла корректное, то файл создается. Я знаю как проверить доступность (или валидность, надо уточнить) пути к папке. Нужно ли проверять корректность названия файла и права доступа? (и есть ли вообще можно способы проверок этого?)

2021-05-15 19:58 UTC, annchous commented on StartingTaskManagerProject/SuperTask.cs
> +        public SuperTask(string taskInfo, DateTime? deadline = null, bool isCompleted = false, Manager<Task> subs = null) : base(taskInfo, isCompleted)
Ну, ты ведь можешь не делать эту проверку и дать пользователю явно понять, что этот параметр не нужен, если он не хочет его задавать сам)

2021-05-15 20:01 UTC, annchous commented on StartingTaskManagerProject/SuperTask.cs
> +        public SuperTask(string taskInfo, DateTime? deadline = null, bool isCompleted = false, Manager<Task> subs = null) : base(taskInfo, isCompleted)
> Или SuperTask не может существовать без дедлайна?

Да по идее может

2021-05-15 20:05 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +        [JsonIgnore] public ReadOnlyDictionary<uint, T> Data => new(Tasks); //for upper-level task usages
> Изначально все-таки большинство свойств хотелось сделать приватными во имя инкапсуляции (это же она? да? да?)

Хех. Не сказала бы, что это исчерпывающее описание концепции инкапсуляции)

2021-05-15 20:10 UTC, annchous commented on StartingTaskManagerProject/Program.cs
> +                            //check for valid path???
А что ты подразумеваешь под проверкой корректности названия файла? Если имеется в виду расширение или ещё что-то, то пусть это останется на совести пользователя. Давай сойдёмся на том, что нас интересует только то, существует ли вообще путь к месту, которое указал пользователь для файла)

2021-05-15 20:11 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +        public Manager(uint nextId = 0, uint countCompleted = 0, SortedDictionary<uint, T> tasks = null)
> Или с ?? что то не так?

Разве что то, что тебе приходится это делать, когда в общем-то и не обязательно) Где-то ниже (или выше) тоже затронула этот вопрос

2021-05-15 20:23 UTC, Patisson4 commented on StartingTaskManagerProject/Manager.cs
> +        public Manager(uint nextId = 0, uint countCompleted = 0, SortedDictionary<uint, T> tasks = null)
Этот конструктор создан для работы json сериализации, пользователю он не должен быть интересен (в теории). Он ругается на отсутствие в конструкторе всех аргументов при вызове (скорее всего потому что сеттеры приватные, но их что-то не хочется делать публичными

2021-05-15 20:28 UTC, Patisson4 commented on StartingTaskManagerProject/SuperTask.cs
> +        public SuperTask(string taskInfo, DateTime? deadline = null, bool isCompleted = false, Manager<Task> subs = null) : base(taskInfo, isCompleted)
То же самое, конструктор по большей части для json сериализации

2021-05-15 20:52 UTC, Patisson4 commented on StartingTaskManagerProject/Manager.cs
> +            if (buf.IsCompleted) //what to do if task already completed?
А стоит ли return убирать? Вроде бы и ускорение кода, а вроде лишний Complete() работает не настолько медленно, чтобы его ускорять

2021-05-15 21:45 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +        public Manager(uint nextId = 0, uint countCompleted = 0, SortedDictionary<uint, T> tasks = null)
ладно

2021-05-15 21:45 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +            if (buf.IsCompleted) //what to do if task already completed?
но тогда он выполнит ещё и CountCompleted++

2021-05-16 07:17 UTC, annchous requested changes

2021-05-16 07:17 UTC, annchous commented on StartingTaskManagerProject/Manager.cs
> +            NextId = manager?.NextId ?? throw new Exception("Failed to deserialize in method Load");
Ну тут немного неочевидно, что ты проверяешь. К тому же это не единственное место использования десериализованного объекта. Я бы остановилась на проверке
```csharp
if (manager == null) throw...
```

2021-05-16 07:17 UTC, annchous commented on StartingTaskManagerProject/Program.cs
> +                            //if SuperTask is completed, then all its subtask must be also completed
А это, кстати, неправда (со слов автора тестового). Так что можно убрать

2021-05-16 07:17 UTC, annchous commented on StartingTaskManagerProject/Program.cs
> +                            Console.WriteLine("Object completed successfully");
Коммент убрать. Object обозвать чем-то более понятным (ну, Task, например?)

2021-05-16 07:17 UTC, annchous commented on StartingTaskManagerProject/Program.cs
> +            while ((input = Console.ReadLine()) != null && input != "") //input comparision may be redundant?
Возможно, чтобы не усложнять себе жизнь, можно сделать `while (true)` цикл и выходить из него только командой /exit и/или какой-то ещё. Ну и просто в начале каждой итерации считывать строку.

2021-05-16 07:17 UTC, annchous commented on StartingTaskManagerProject/Program.cs
> +                            //although method is called 'Remove', command is called 'Delete', that's why there is such a comment
Я бы догадалась и так, что к чему)

2021-05-16 13:18 UTC, annchous approved these changes

2021-05-16 13:47 UTC, merged